"""empty message

Revision ID: df71a2016e46
Revises: bc790fb07c24
Create Date: 2022-02-16 13:30:04.114498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df71a2016e46'
down_revision = 'bc790fb07c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('start_time', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genres', 'start_time')
    # ### end Alembic commands ###
